[package]
name = "cue_lib"
description = "cuesheet library"
keywords = ["cue", "cuesheet", "file-format", "library"]
license = "Apache-2.0"
version = "0.1.0"
edition = "2024"
authors = ["Timur Olur <pm@smdd.dev>"]
documentation = "https://github.com/SuperioOne/cue_rs"
homepage = "https://github.com/SuperioOne/cue_rs"
repository = "https://github.com/SuperioOne/cue_rs"

[features]
default = []
alloc = ["serde?/alloc"]
metadata = []
ean = []
upc = []
serde = ["dep:serde"]

[dependencies]
serde = { version = "1", default-features = false, optional = true, features = [
        "derive",
] }
