[package]
name = "cue_lib"
description = "cuesheet library"
keywords = ["cue", "cuesheet", "file-format", "library"]
license = "Apache-2.0"
version = "0.1.0"
edition = "2024"
authors = ["Timur Olur <pm@smdd.dev>"]
documentation = "https://codeberg.org/SuperiorOne/cue_lib"
homepage = "https://codeberg.org/SuperiorOne/cue_lib"
repository = "https://codeberg.org/SuperiorOne/cue_lib"
exclude = ["/.gitea", "rustfmt.toml"]

[features]
default = []
alloc = ["serde?/alloc"]
metadata = []
ean = []
upc = []
serde = ["dep:serde"]

[dependencies]
serde = { version = "1", default-features = false, optional = true, features = [
        "derive",
] }

[package.metadata.docs.rs]
all-features = true
