name: publish-crates-io
on:
  push:
    tags:
      - v*
jobs:
  publish-binaries:
    defaults:
      run:
        shell: bash
    runs-on: akashi
    container:
      image: gitea-service:80/actions/arch-action-runner-full:latest
      options: "--security-opt seccomp=unconfined --security-opt apparmor=unconfined --device /dev/fuse:rw"
      credentials:
        username: ${{secrets.ACTION_USER}}
        password: ${{secrets.ACTION_TOKEN}}
    steps:
      - uses: http://gitea-service/actions/checkout@v4
        with:
          show-progress: false
          submodules: true
      - name: Setup rustup targets
        run: |
          rustup default stable;
      - name: Run tests
        run: cargo test --all-features
      - name: Publish crate to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
      - name: Generate release body from changelog
        run: >
          VERSION="$(cargo metadata --no-deps --offline --format-version 1 | jq -r '.packages[] | select(.name == "cue_lib") | .version')";
          cat ./changelog | awk -v version="^# v${version}" '$0 ~ version {start=1;next}/^# v.*$/{start=0}start' > release_body.txt;
          cat ./release_body.txt;
      - name: Crete new release on local
        uses: http://gitea-service/actions/gitea-release-action@main
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: false
        with:
          api_key: ${{secrets.ACTION_TOKEN}}
          title: ${{vars.GITEA_REF_NAME}}
          body_path: "./release_body.txt"
      - name: Crete new release on codeberg
        uses: http://gitea-service/actions/forgejo-release-action@main
        with:
          direction: upload
          url: https://codeberg.org/SuperiorOne/cue_lib
          token: ${{secrets.CODEBERG_TOKEN}}
          title: ${{vars.GITEA_REF_NAME}}
          tag: ${{vars.GITEA_REF_NAME}}
          release-notes-file: "./release_body.txt"
