[package]
name = "cue_ffmpeg"
edition = "2024"
description = "cue_tool specific functions for splitting audio streams and setting metadata using a subset of ffmpeg's libav."
license = "GPL-2.0"
version.workspace = true
authors.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cue_ffmpeg_sys = { path = "../cue_ffmpeg_sys" }
